= Quarkus Business Score

include::./includes/attributes.adoc[]

This extension offers a convenient way to detect application _zombies_, i.e. applications that live and communicate but **do not produce any business value**.
The "business value" means anything that helps to solve a problem of an application user. 
Infrastructure stuff (logs, stats, metrics, health checks) usually does not produce a business value.

== Key concepts

In a nutshell, this extension manages the **business score** which is a numeric representation of the business value. 
An application emits **score records** to increase the business score, either directly with the `BusinessScore` API or with an interceptor binding.
The records are only kept for the specific amount of time - **time window**. 
The sum of all score records in the current time window is the **current business score**. 
The **zombie threshold** defines the point at which the application is considered a _zombie_.
An external system or the application itself can periodically check the business score and react appropriately.

== Core

If you want to use this extension, you need to add the `io.quarkiverse.businessscore:quarkus-business-score` extension first.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.businessscore</groupId>
    <artifactId>quarkus-business-score</artifactId>
    <version>{project-version}</version>
</dependency>
----

=== How to score

Quarkus provides a CDI bean of type `io.quarkiverse.businessscore.BusinessScore` that can be used to increase and also to query the current score.

.`BusinessScore` example
[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import io.quarkiverse.businessscore.BusinessScore;

@ApplicationScoped
public class MyService {

   @Inject
   BusinessScore bs; <1>
   
   public void doSomeBusiness() {
     bs.score(10); <2>
     // ...
   }

}
----
<1> Inject the business score of the current application.
<2> Increase the business score by `10`.

Alternatively, the `@io.quarkiverse.businessscore.Scored` interceptor binding can be used to increase the score using an interceptor.

.`@Scored` example
[source,java]
----
import 
import io.quarkiverse.businessscore.BusinessScore;

@ApplicationScoped
public class MyService {

   @Scored(10) <1>
   public void doSomeBusiness() {
     // ...
   }

}
----
<1> Increase the business score of the current application by `10`.

=== How to check the business score

You can inject the `io.quarkiverse.businessscore.BusinessScore` and check the "zombie" status with the `BusinessScore#test()` method.

.`BusinessScore` example
[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import io.quarkiverse.businessscore.BusinessScore;

@ApplicationScoped
public class MyService {

   @Inject
   BusinessScore bs; <1>
   
   public void check() {
     if (bs.test().isZombie()) {
        // TODO warn the application admin!
     }
   }

}
----
<1> Inject the business score of the current application.

== HTTP module

This module integrates with the https://quarkus.io/guides/http-reference[HTTP extension] and registers two additional endpoints:

- `/q/business-score` - shows the current score, zombie status, etc.
- `/q/business-score/records` - shows all score records in the current time window
 

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.businessscore</groupId>
    <artifactId>quarkus-business-score-http</artifactId>
    <version>{project-version}</version>
</dependency>
----

.`/q/business-score` response example
[source,json]
----
{
    "serverTime": "2024-06-13T15:14:20.794528118",
    "application": {
        "name": "quarkus-business-score-integration-tests",
        "version": "999-SNAPSHOT"
    },
    "zombie": false,
    "score": 1,
    "zombieThreshold": 20,
    "initialZombieThreshold": 10,
    "timeWindow": "PT72H",
    "initialTimeWindow": "PT168H"
}
----

.`/q/business-score/records` response example
[source,json]
----
{
    "serverTime": "2024-06-13T15:14:21.259640872",
    "application": {
        "name": "quarkus-business-score-integration-tests",
        "version": "999-SNAPSHOT"
    },
    "records": [
        {
            "value": 1,
            "timestamp": "2024-06-13T13:14:20.735Z"
        }
    ]
}
----

[[scheduler_module]]
== Scheduler module

This module integrates with the https://quarkus.io/guides/scheduler-reference[Scheduler] extension and registers an additional `@Scheduled` method.
I.e. the current application is tested periodically and if a _zombie_ is detected then a warning message is logged and a CDI event of type `io.quarkiverse.businessscore.BusinessScore.ZombieStatus` is fired synchronously.
The CRON trigger used to schedule an automatic self-test can be configured with the `quarkus.business-score.scheduler.cron` configuration property.

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.businessscore</groupId>
    <artifactId>quarkus-business-score-scheduler</artifactId>
    <version>{project-version}</version>
</dependency>
----

.CDI observer example
[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;

@ApplicationScoped
public class MyService {

   void onZombie(@Observes BusinessScore.ZombieStatus status) { <1>
      // TODO warn the application admin!
   }

}
----
<1> Observe the `ZombieStatus` and react appropriately.

== Health module

This module integrates with the https://quarkus.io/guides/smallrye-health[SmallRye Health] extension and registers a https://smallrye.io/docs/smallrye-health/3.0.1/wellness.html[`@Wellness` health check] automatically.
The health check is accessible through the `/q/health/well` endpoint.
 
[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.businessscore</groupId>
    <artifactId>quarkus-business-score-health</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Mailer module

This module integrates with the https://quarkus.io/guides/mailer-reference[Mailer] extension and sends an email automatically when a self-test perfomed by the <<scheduler_module>> fails, i.e. when a zombie is detected.
The `from`, `to` and `subject` fields are configurable.

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.businessscore</groupId>
    <artifactId>quarkus-business-score-mailer</artifactId>
    <version>{project-version}</version>
</dependency>
----
 

[[extension-configuration-reference]]
=== Extension Configuration Reference

include::includes/quarkus-business-score.adoc[leveloffset=+1, opts=optional]

include::includes/quarkus-business-score-http.adoc[leveloffset=+1, opts=optional]

include::includes/quarkus-business-score-scheduler.adoc[leveloffset=+1, opts=optional]

include::includes/quarkus-business-score-mailer.adoc[leveloffset=+1, opts=optional]

